version: "3.9"

services:
  api:
    build: .
    container_name: image-api
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - .:/app            # Sincroniza seu código local com o container
      - /app/node_modules # Evita sobrescrever os node_modules locais
    depends_on:
      - db
    environment:
      NODE_ENV: development
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: nestjs_serverless
    command: npm run dev

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_serverless
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
